// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQSPHDh7iysYrE8O77Cn2J8TqxM8vxKs',
    appId: '1:144953859334:web:5ba2c0d0a150920ae81287',
    messagingSenderId: '144953859334',
    projectId: 'myapps-dae',
    authDomain: 'myapps-dae.firebaseapp.com',
    storageBucket: 'myapps-dae.appspot.com',
    measurementId: 'G-H20XMV660B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSrgIlrfU49XhR3AiILr9TO7J2UwkpNY',
    appId: '1:144953859334:android:b0887781efe81603e81287',
    messagingSenderId: '144953859334',
    projectId: 'myapps-dae',
    storageBucket: 'myapps-dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgABdo-2cFYeNq0FRytfyRmTPkicfwzw',
    appId: '1:144953859334:ios:2accfc7f679a3b96e81287',
    messagingSenderId: '144953859334',
    projectId: 'myapps-dae',
    storageBucket: 'myapps-dae.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgABdo-2cFYeNq0FRytfyRmTPkicfwzw',
    appId: '1:144953859334:ios:04cb1de494a6bebde81287',
    messagingSenderId: '144953859334',
    projectId: 'myapps-dae',
    storageBucket: 'myapps-dae.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
